### ISSUE TITLE
fail to build driver

### ISSUE THREAD

**Issue by TotalSonic** [bondagit/ravenna-alsa-lkm#15]
Greetings - in attempting to build the driver on Ubuntu 23.10 I get this error:
      |                 ^~~~
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/module_interface.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/module_netlink.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/module_timer.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/EtherTubeNetfilter.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/RTP_streams_manager.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/RTP_audio_stream.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/RTP_stream.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/RTP_stream_info.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/MTAL_EthUtils.o
  CC [M]  /home/steveb/ravenna-alsa-lkm/driver/MTAL_LKernelAPI.o
/home/steveb/ravenna-alsa-lkm/driver/MTAL_LKernelAPI.c:94:10: fatal error: stdarg.h: No such file or directory
   94 | #include <stdarg.h>
      |          ^~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:251: /home/steveb/ravenna-alsa-lkm/driver/MTAL_LKernelAPI.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.5.0-14-generic/Makefile:2037: /home/steveb/ravenna-alsa-lkm/driver] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.5.0-14-generic'
make: *** [Makefile:14: modules] Error 2
steveb@TSM-i7-UB:~/ravenna-alsa-lkm/driver$

**Comment by bondagit** [comment]
check your toolchain.

**Comment by TotalSonic** [comment]
Andrea - thanks so much for your reply. How do I check my toolchain? What am I checking for in it?

Best regards,
Steve Berson
Total Sonic Media
digital & analog audio mastering
http://totalsonic.net
+1-718-594-0859

Mar 23, 2024 9:46:52 AM Andrea Bondavalli ***@***.***>:

**Comment by bondagit** [comment]
Hi Steve,

Check if the following helps you.
https://stackoverflow.com/questions/54480765/how-can-i-solve-stdarg-h-no-such-file-or-directory-while-compiling-out-of-tree-l￼
How can I solve stdarg.h No such file or directory while compiling out-of-tree Linux kernel module?
stackoverflow.com


Kind regards,
Andrea
