### ISSUE TITLE
libcurl3 has been obsoleted in favour of libcurl4; Butler will not run on newer linux.

### ISSUE THREAD

**Issue by cortices** [bondagit/ravenna-alsa-lkm#3]
The Butler public binary depends on libcurl3, which is no longer available for Ubuntu 20.04 and others. It should be re-compiled with libcurl4 support and re-released.

**Comment by bondagit** [comment]
I have forker the Ravenna driver and added patches to the AES67-daemon branch only for using it with the AES67 Linux Daemon project. 
Pleaee checkout the master branch of following repo:
https://github.com/bondagit/aes67-linux-daemon
And use the build.sh script to compile everything you need. 
See Prerequisite and How to build sections in the Readme file for additional iinfo.

**Comment by bondagit** [comment]
I don't provide support to Butler user space. I can only assist on the driver in the aes67-daemon branch of this repo.
[aes67-linux-daemon](https://github.com/bondagit/aes67-linux-daemon) provides an alteranative to the Butler user space daemon.
