### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by hifi25nl** [bondagit/ravenna-alsa-lkm#5]
[audiolinux@archlinux driver]$ make
make -C /lib/modules/5.12.1-arch1-1/build/ M=/media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver modules
make[1]: Entering directory '/usr/lib/modules/5.12.1-arch1-1/build'
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/c_wrapper_lib.o
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/audio_driver.o
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/manager.o
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/module_main.o
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/PTP.o
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/module_interface.o
/media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/module_interface.c:63:25: error: expected declaration specifiers or ‘...’ before string constant
   63 | MODULE_SUPPORTED_DEVICE("{{ALSA,Merging RAVENNA}}");
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:271: /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver/module_interface.o] Error 1
make[1]: *** [Makefile:1851: /media/linux/Downloads/Temp/ravenna-alsa-lkm-1.1/driver] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.12.1-arch1-1/build'
make: *** [Makefile:14: modules] Error 2

**Comment by hifi25nl** [comment]
The same on kernels:
5.11.4-rt11-13-rt-bfq-dev 
5.10.27-rt36-1-rt-lts 

with the aes67 branch

**Comment by bondagit** [comment]
The the MODULE_SUPPORTED_DEVICE macro was removed from the kernel entirely.
Try to comment the line 63 in the file 3rdparty/ravenna-alsa-lkm/driver/module_interface.c :

**Comment by hifi25nl** [comment]
OK, removing it compilation finish more or less correctly, with some error about unused variables

**Comment by bondagit** [comment]
Ok, I will add a patch for this.

**Comment by hifi25nl** [comment]
Ok thanks. Now arch package is fixed:
https://aur.archlinux.org/packages/ravenna-alsa-lkm-dkms/
