### ISSUE TITLE
PTP_WATCHDOG_ELAPSE off by 1000

### ISSUE THREAD

**Issue by glance-** [bondagit/ravenna-alsa-lkm#7]
According to the PTP_WATCHDOG_ELAPSE comment `we assume to receive at least one sync each 2s` its supposed to be 2s.

```
#define PTP_WATCHDOG_ELAPSE		20000000	// we assume to receive at least
#define NS_2_REF_UNIT 100000 // ns is the linux time unit

void get_clock_time(uint64_t* clock_time)
{
    ktime_t kt_now;
    kt_now = ktime_get();
    *clock_time = (uint64_t)ktime_to_ns(kt_now);
}

...
    uint64_t ui64CurrentRTXClockTime;
    get_clock_time(&ui64CurrentRTXClockTime);
    ui64CurrentRTXClockTime /= NS_2_REF_UNIT; // [100us]

...
        uint64_t ui64WatchDogElapse = ui64CurrentRTXClockTime - self->m_ui64LastWatchDogTime;
        if(ui64WatchDogElapse >= PTP_WATCHDOG_ELAPSE)

```

As I read that and have tested it for is that PTP_WATCHDOG_ELAPSE is in 100us as unit. That means that PTP_WATCHDOG_ELAPSE is 20000000 * 100us = 2000s.

I'd suggest cutting it by 1000, because then the rest of the code behaves as expected when a ptp clock is lost.

**Comment by bondagit** [comment]
good catch !
It looks like a watchdog mechanism for the PTP master clock was already in place then.
This should actually transition the master clock status to unlocked in case no SYNC message is received from the master for more than 2secs.
For the same purpose I implemented a similar mechanism some time ago that triggers on no ANNOUNCE message from the master for more than 5 sec.  See [cdd64d2](https://github.com/bondagit/ravenna-alsa-lkm/commit/cdd64d2358b684e7d9d3eacc12f547b3f58abd5e) . This one also resets the master clock info.

**Comment by glance-** [comment]
I've done some more testing on this and I didn't get the clear timeout at 2000s as I expected, but rather saw it after 3890s , so either there where some overflow that happened and that caused the watchdog mechanism to not trigger, or there's something else I'm missing.

When I cut PTP_WATCHDOG_ELAPSE with 1000x it reliably acted as expected in my test cases. It could have bin that it cut at 3.9s instead of 2s (same scaling as above) but it's hard to time with my current test setup, but anyway 3.9s is good enough for me.

**Comment by glance-** [comment]
I never saw https://github.com/bondagit/aes67-linux-daemon/issues/87 or https://github.com/bondagit/ravenna-alsa-lkm/commit/cdd64d2358b684e7d9d3eacc12f547b3f58abd5e so this was just independently finding the issue and digging around for a solution.
